with open("src/pages/PrepMode.jsx", "r", encoding="utf-8") as f:
    content = f.read()

import re

old_qa_parse = """          if (typeof parsed === 'string') {
            parsed = JSON.parse(parsed.replace(/```json/g, '').replace(/```/g, ''));
          }"""

new_qa_parse = """          if (typeof parsed === 'string') {
            let cleanStr = parsed.replace(/```json/g, '').replace(/```/g, '').trim();
            // Fix unescaped backslashes commonly generated by LLMs in math/latex
            cleanStr = cleanStr.replace(/\\\\(?!["\\\\/bfnrt])/g, "\\\\\\\\");
            // Also fix actual newlines inside strings
            cleanStr = cleanStr.replace(/\\n/g, "\\\\n");
            try {
              parsed = JSON.parse(cleanStr);
            } catch (e) {
              // Last resort fallback: aggressively escape all backslashes
              cleanStr = parsed.replace(/```json/g, '').replace(/```/g, '').trim().replace(/\\\\/g, "\\\\\\\\");
              parsed = JSON.parse(cleanStr);
            }
          }"""

content = content.replace(old_qa_parse, new_qa_parse)

with open("src/pages/PrepMode.jsx", "w", encoding="utf-8") as f:
    f.write(content)
print("done")
